name: Build & Publish Debug APK
'on':
  workflow_dispatch:
    inputs:
      name:
        description: Release Name
        required: true
        default: inure_manual_debug
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: set up NDK r24b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: debug # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: app
      - name: Generate version.txt for Hub release
        run: ./gradlew generateVersionTxt
      - name: Releasing using Hub
        uses: valley-fordham/action-release-debugapk@master
        env:

          APP_FOLDER: app
          RELEASE_TITLE: '${{ github.event.inputs.name }}'
