name: Build & Publish Debug APK
'on':
  workflow_dispatch:
    inputs:
      name:
        description: Release Name
        required: true
        default: inure_manual_debug
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up NDK r24b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Generate version.txt for Hub release
        run: ./gradlew generateVersionTxt
      - name: Releasing using Hub
        uses: valley-fordham/action-release-debugapk@master
        env:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
          APP_FOLDER: app
          RELEASE_TITLE: '${{ github.event.inputs.name }}'
